import { FinancialBackfillBatchStatus, FinancialDataOrigin, Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { FINANCIAL_AUDIT_ACTIONS } from "@/lib/finance/audit-actions";
import { ZERO_MONEY } from "@/lib/finance/money";

export const HISTORICAL_BACKFILL_VERSION = "f3-lyd-zero-adjustments-v1";
export type BackfillPreview = { totalOrders: number; nativeOrders: number; candidates: number; currencyEligible: number; zeroDiscountEligible: number; zeroTaxEligible: number; missingReliableTotals: number; missingBranch: number; missingPaymentMethod: number; missingPaidAt: number; missingReceiver: number; noPayment: number; deterministic: number; partial: number; manualReconciliation: number; legacyUnknown: number; orderUpdates: number; itemUpdates: number };

function native(order: { financialDataOrigin: FinancialDataOrigin | null; payments: { status: string }[] }) { return order.financialDataOrigin === FinancialDataOrigin.NATIVE && order.payments.some((p) => p.status === "CAPTURED"); }
function summarize(orders: Array<{ financialDataOrigin: FinancialDataOrigin | null; currency: string | null; discountTotal: Prisma.Decimal | null; taxTotal: Prisma.Decimal | null; subtotalAmount: Prisma.Decimal | null; totalAmount: Prisma.Decimal | null; branchId: string | null; items: Array<{ lineDiscountTotal: Prisma.Decimal | null; lineTaxTotal: Prisma.Decimal | null }>; payments: Array<{ status: string; method: unknown; paidAt: Date | null; receivedByUserId: string | null }> }>): BackfillPreview {
  const r: BackfillPreview = { totalOrders: orders.length, nativeOrders: 0, candidates: 0, currencyEligible: 0, zeroDiscountEligible: 0, zeroTaxEligible: 0, missingReliableTotals: 0, missingBranch: 0, missingPaymentMethod: 0, missingPaidAt: 0, missingReceiver: 0, noPayment: 0, deterministic: 0, partial: 0, manualReconciliation: 0, legacyUnknown: 0, orderUpdates: 0, itemUpdates: 0 };
  for (const o of orders) { if (native(o)) { r.nativeOrders++; continue; } r.candidates++; const p=o.payments.find(x=>x.status==="CAPTURED"); const critical=!o.totalAmount||!o.subtotalAmount||!o.branchId||!p?.method||!p.paidAt||!p.receivedByUserId; if(!o.currency)r.currencyEligible++;if(o.discountTotal===null)r.zeroDiscountEligible++;if(o.taxTotal===null)r.zeroTaxEligible++;if(!o.totalAmount||!o.subtotalAmount)r.missingReliableTotals++;if(!o.branchId)r.missingBranch++;if(!p?.method)r.missingPaymentMethod++;if(!p?.paidAt)r.missingPaidAt++;if(!p?.receivedByUserId)r.missingReceiver++;if(!o.payments.length)r.noPayment++;r.itemUpdates+=o.items.filter(i=>i.lineDiscountTotal===null||i.lineTaxTotal===null).length;r.orderUpdates++;if(critical)r.legacyUnknown++;else r.deterministic++; } return r;
}
export async function previewHistoricalBackfill(businessId: string) { const orders=await prisma.order.findMany({where:{businessId},include:{items:true,payments:true}}); return summarize(orders); }
export async function applyHistoricalBackfill(input:{businessId:string;actorUserId?:string;backfillVersion:string;idempotencyKey:string;confirmationToken:string}) {
 if(input.confirmationToken!=="APPLY_FINANCIAL_BACKFILL")throw new Error("BACKFILL_CONFIRMATION_REQUIRED"); return prisma.$transaction(async tx=>{const where={businessId_backfillVersion_idempotencyKey:{businessId:input.businessId,backfillVersion:input.backfillVersion,idempotencyKey:input.idempotencyKey}};const old=await tx.financialBackfillBatch.findUnique({where});if(old?.status===FinancialBackfillBatchStatus.COMPLETED)return{batch:old,replayed:true};const orders=await tx.order.findMany({where:{businessId:input.businessId},include:{items:true,payments:true}});const preview=summarize(orders);const batch=old??await tx.financialBackfillBatch.create({data:{businessId:input.businessId,actorUserId:input.actorUserId,backfillVersion:input.backfillVersion,idempotencyKey:input.idempotencyKey,status:FinancialBackfillBatchStatus.RUNNING,previewSummary:JSON.stringify(preview),startedAt:new Date()}});for(const o of orders){if(native(o))continue;const d:Prisma.OrderUpdateInput={};if(!o.currency)d.currency="LYD";if(o.discountTotal===null)d.discountTotal=ZERO_MONEY;if(o.taxTotal===null)d.taxTotal=ZERO_MONEY;if(o.financialDataOrigin===null)d.financialDataOrigin=FinancialDataOrigin.LEGACY_UNKNOWN;if(!o.branchId&&o.branchDataOrigin===null)d.branchDataOrigin=FinancialDataOrigin.LEGACY_UNKNOWN;if(Object.keys(d).length)await tx.order.update({where:{id:o.id},data:d});for(const i of o.items){const x:Prisma.OrderItemUpdateInput={};if(i.lineDiscountTotal===null)x.lineDiscountTotal=ZERO_MONEY;if(i.lineTaxTotal===null)x.lineTaxTotal=ZERO_MONEY;if(Object.keys(x).length)await tx.orderItem.update({where:{id:i.id},data:x});}}const done=await tx.financialBackfillBatch.update({where:{id:batch.id},data:{status:FinancialBackfillBatchStatus.COMPLETED,appliedSummary:JSON.stringify(preview),completedAt:new Date()}});await tx.auditLog.create({data:{actorUserId:input.actorUserId,businessId:input.businessId,action:FINANCIAL_AUDIT_ACTIONS.BACKFILL_APPLIED,entityType:"FinancialBackfillBatch",entityId:batch.id,afterSnapshot:JSON.stringify({backfillVersion:input.backfillVersion,candidates:preview.candidates})}});return{batch:done,replayed:false};});
}
