"use client";
import { useActionState } from "react";
import { PosPaymentMethod } from "@prisma/client";
import { initialReconciliationState, submitLegacyReconciliation } from "./actions";

export function LegacyReconciliationForm({ locale, order, branches, receivers }: { locale: string; order: { id: string; createdAt: string; completedAt: string | null; items: Array<{ id: string; quantity: string; productName: string; productPrice: string }> }; branches: Array<{ id: string; code: string; nameAr: string; archivedAt: boolean }>; receivers: Array<{ id: string; name: string }> }) {
  const [state, action, pending] = useActionState(submitLegacyReconciliation, initialReconciliationState);
  return <main className="mx-auto max-w-3xl p-6"><h1 className="text-xl font-bold">تأكيد تسوية مالية تاريخية</h1><p className="mt-2 rounded border border-amber-300 bg-amber-50 p-3 text-sm">تاريخ الإكمال ليس تلقائياً تاريخ الدفع. سعر المنتج الحالي للمرجع فقط وليس دليلاً لسعر البيع التاريخي. ستنشئ العملية دفعة مقبوضة رسمية غير قابلة للتعديل.</p><form action={action} className="mt-5 space-y-5"><input type="hidden" name="locale" value={locale}/><input type="hidden" name="orderId" value={order.id}/><section><h2 className="font-semibold">الأسعار وقت البيع</h2>{order.items.map((item) => <label key={item.id} className="mt-2 block rounded border p-3">{item.productName} · الكمية {item.quantity}<span className="block text-xs text-zinc-500">السعر الحالي للمرجع فقط: {item.productPrice}</span><input required name={`price:${item.id}`} inputMode="decimal" pattern="\d+(\.\d{1,3})?" placeholder="سعر الوحدة وقت البيع" className="mt-2 w-full rounded border px-3 py-2" /></label>)}</section><label className="block">الفرع<select required name="branchId" className="mt-1 w-full rounded border p-2"><option value="">اختر الفرع</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.code} — {branch.nameAr}{branch.archivedAt ? " (مؤرشف)" : ""}</option>)}</select></label><label className="block">طريقة الدفع<select required name="method" className="mt-1 w-full rounded border p-2"><option value="">اختر الطريقة</option>{Object.values(PosPaymentMethod).map((method) => <option key={method}>{method}</option>)}</select></label><label className="block">تاريخ ووقت الدفع<input required type="datetime-local" name="paidAt" className="mt-1 w-full rounded border p-2" /></label><label className="block">المستلم<select required name="receiverUserId" className="mt-1 w-full rounded border p-2"><option value="">اختر المستلم</option>{receivers.map((receiver) => <option key={receiver.id} value={receiver.id}>{receiver.name}</option>)}</select></label><label className="block">مرجع الدفع (اختياري)<input name="reference" className="mt-1 w-full rounded border p-2" /></label><label className="block">وصف الدليل<textarea required name="evidenceDescription" className="mt-1 w-full rounded border p-2" /></label><label className="block">سبب التسوية<textarea required name="reason" className="mt-1 w-full rounded border p-2" /></label><label className="flex gap-2"><input required type="checkbox" name="confirmImmutable" value="true"/> أؤكد الأسعار والمجموع المحسوب والخطوة النهائية وعدم قابلية التعديل.</label>{state.error ? <p className="text-sm text-red-700">{state.error}</p> : null}{state.success ? <p className="text-sm text-emerald-700">{state.success}</p> : null}<button disabled={pending} className="rounded bg-emerald-700 px-4 py-2 font-semibold text-white">{pending ? "جارٍ الحفظ" : "تأكيد وإنشاء الدفعة المقبوضة"}</button></form></main>;
}
